In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ["bharat is a data scientist",
        " i love AI/Ml",
        "python is good langauge",
        "i am using tensorFlow",
        "my favorite movie is iron man 3"]

In [3]:
# define vocabulary size
voc_size = 10000

In [4]:
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr

[[856, 6329, 979, 1720, 4173],
 [4390, 9591, 7685, 5528],
 [8861, 6329, 2542, 2873],
 [4390, 4880, 2127, 3589],
 [6174, 9087, 2788, 6329, 4222, 5110, 6059]]

this is showing index of the words in the vocab eg. > if "bhaart" is matching atindex of 9546 index others are 0

In [5]:
# word Embeding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
#from tensorflow.keras.utils import pad_sequences
import numpy as np


In [6]:
#setting max sent length
sent_len = 8
embeded_docs = pad_sequences(one_hot_repr, padding= 'pre', maxlen= sent_len)
print(embeded_docs)

[[   0    0    0  856 6329  979 1720 4173]
 [   0    0    0    0 4390 9591 7685 5528]
 [   0    0    0    0 8861 6329 2542 2873]
 [   0    0    0    0 4390 4880 2127 3589]
 [   0 6174 9087 2788 6329 4222 5110 6059]]


In [7]:
# Feature representation
dim = 10 # there are 300 dimensions in the trained model

model = Sequential()
model.add(Embedding(voc_size,dim,input_length = sent_len))
model.compile('adam','mse')

c:\Users\lenovo\Desktop\GenAI\ANN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
embeded_docs[0]

array([   0,    0,    0,  856, 6329,  979, 1720, 4173], dtype=int32)

In [10]:
model.predict(embeded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 476ms/step


array([[[-3.5704300e-04, -8.5904822e-03, -4.2212117e-02,  2.1533433e-02,
         -3.2938182e-02, -4.0985812e-02, -3.3674277e-02, -1.0322440e-02,
         -2.7520597e-02, -1.6448714e-02],
        [-3.5704300e-04, -8.5904822e-03, -4.2212117e-02,  2.1533433e-02,
         -3.2938182e-02, -4.0985812e-02, -3.3674277e-02, -1.0322440e-02,
         -2.7520597e-02, -1.6448714e-02],
        [-3.5704300e-04, -8.5904822e-03, -4.2212117e-02,  2.1533433e-02,
         -3.2938182e-02, -4.0985812e-02, -3.3674277e-02, -1.0322440e-02,
         -2.7520597e-02, -1.6448714e-02],
        [ 1.9484367e-02, -4.7162414e-02,  1.8666614e-02, -1.6606342e-02,
         -2.0842755e-02, -1.1701714e-02, -3.1349443e-02, -1.3983976e-02,
         -2.0437503e-02,  4.3666791e-02],
        [-2.6274845e-04,  9.0465769e-03, -3.8125169e-02, -4.6459403e-02,
         -4.0840626e-02,  1.1283517e-02,  3.5201702e-02, -3.6687948e-02,
          2.2350494e-02, -2.3498654e-02],
        [ 2.0413760e-02,  4.8946764e-02, -9.1597550e-03, -2.

array([   0,    0,    0, 9546, 2499, 9853, 3824, 7743], dtype=int32)

this sentance has been converted to>>

[ 9.04599577e-03,  6.72154501e-03,  4.72785495e-02,
         -3.00797224e-02, -1.60469040e-02,  1.91533901e-02,
         -3.17410119e-02, -1.04019865e-02,  3.42671610e-02,
          1.57937445e-02]